config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: %i[create destroy]

  get 'pages/timeline'
  post :notifications, to: 'notifications#mark_all_readed'

  resources :tweets, only: %i[create edit update destroy]
  resources :likes, only: %i[create destroy], param: 'likeable_id'
  resources :comments, only: %i[create destroy]
  resources :retweets, only: %i[create destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment
  include PublicActivity::Model

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  belongs_to :user

  validates_length_of :comment, maximum: 140

  FORMAT = AutoHtml::Pipeline.new(
    AutoHtml::HtmlEscape.new,
    AutoHtml::Link.new(target: '_blank', rel: 'nofollow'),
    AutoHtml::SimpleFormat.new
  )

  def comment=(c)
    super(c)
    self[:comment] = FORMAT.call(c)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: [:create]
  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save!
    @comment.create_activity key: 'comment.created', owner: current_user, recipient: @commentable.user
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
  end

  private

  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="card-footer">
    <%= gravatar_tag comment.user.email, size: 25, html: {class: 'img-fluid'} %>
    <span><%= comment.user.username %></span>
    <span>رد على تغريدة</span>
    <%= content_tag :time, '', class: 'timeago', datetime: comment.created_at.localtime %>
    <% if user_signed_in? && current_user.id == comment.user.id %>
    <%= link_to('حذف', comment_path(comment), method: :delete, remote: true, class: 'btn btn-sm btn-danger') %>
    <% end %>
  </div>
  <div class="card-body">
    <%= raw(comment.comment) %>
  </div>
</div>

app/views/comments/_form.html.erb
<p class="text-center mb-0">عدد الرود: <span id="comments-<%= tweet.id %>-count"><%= tweet.comments.size %></span></p>

<%= form_tag comments_path(commentable_type: 'tweet', commentable_id: tweet.id), method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag :comment_text, nil, placeholder: 'ردك', class: 'form-control' %>
  </div>
  <%= submit_tag 'ردك', class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$('#comments-<%= @comment.commentable.id %>').prepend('<%= j render @comment %>')
c_count = $('#comments-<%= @comment.commentable.id %>-count').text()
$('#comments-<%= @comment.commentable.id %>-count').text(parseInt(c_count) + 1)
$('.tweet-<%= @comment.commentable.id %> #comment_text').val('')

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove()
c_count = $('#comments-<%= @comment.commentable.id %>-count').text()
$('#comments-<%= @comment.commentable.id %>-count').text(parseInt(c_count) - 1)