config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: %i[create destroy]

  get 'pages/timeline'
  post :notifications, to: 'notifications#mark_all_readed'

  resources :tweets, only: %i[create edit update destroy]
  resources :likes, only: %i[create destroy], param: 'likeable_id'
  resources :comments, only: %i[create destroy]
  resources :retweets, only: %i[create destroy]
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  include PublicActivity::Model
  belongs_to :retweeter, class_name: 'User'
  belongs_to :source_tweet, class_name: 'Tweet'
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    retweet = current_user.retweets.new(source_tweet_id: params[:tweet_id])
    if retweet.save
      retweet.create_activity key: 'retweet.created', owner: current_user, recipient: retweet.source_tweet.user
      redirect_to user_path(current_user.username), notice: 'تم اعادة التغريدة'
    else
      redirect_to fullback_location: root_path, alert: 'حدث خطأ ما!'
    end
  end

  def destroy
    retweet = current_user.retweets.find(params[:id])
    retweet.destroy
    redirect_to user_path(current_user.username), notice: 'تم حذف اعادة التغريدة'
  end
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/views/retweets/_retweet.html.erb
<div class="card mb-3 tweet-<%= retweet.source_tweet.id %>">
    <div class="card-header bg-success border-success text-white">
      قام <%= retweet.retweeter.username %> بإعادة تغريدة هذا <%= content_tag :time, '', class: 'timeago', datetime: retweet.created_at.localtime %>
      <% if user_signed_in? && retweet.retweeter_id == current_user.id %>
      <%= link_to 'حذف', retweet_path(retweet), method: :delete, class: "btn btn-sm btn-danger" %>
      <% end %>
    </div>
    <div class="card-header">
        <%= gravatar_tag retweet.source_tweet.user.email, size: 25, html: {class: 'img-fluid'} %>
        <span><%= retweet.source_tweet.user.username %></span>
        <span>غرد</span>
        <%= content_tag :time, '', class: 'timeago', datetime: retweet.source_tweet.created_at.localtime %>
        <% if user_signed_in? && current_user == retweet.source_tweet.user %>
        <%= link_to 'تعديل', edit_tweet_path(retweet.source_tweet), class: "btn btn-sm btn-primary" %>
        <span>|</span>
        <%= link_to 'حذف', tweet_path(retweet.source_tweet), method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
    </div>
    <div class="card-body">
        <%= raw(retweet.source_tweet.content_html) %>
        <%= render 'tweets/like_and_dislike_button', tweet: retweet.source_tweet %>
        <%= render('tweets/retweet_button', tweet: retweet.source_tweet) if user_signed_in? && retweet.source_tweet.user_id != current_user.id %>
    </div>
    <hr>
    <div class="card-body">
    <%= render 'comments/form', tweet: retweet.source_tweet %>
    </div>
    <div id="comments-<%= retweet.source_tweet.id %>">
      <%= render retweet.source_tweet.comments.reverse %>
    </div>
</div>