config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: %i[create destroy]

  get 'pages/timeline'
  post :notifications, to: 'notifications#mark_all_readed'

  resources :tweets, only: %i[create edit update destroy]
  resources :likes, only: %i[create destroy], param: 'likeable_id'
  resources :comments, only: %i[create destroy]
  resources :retweets, only: %i[create destroy]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  include PublicActivity::Model

  acts_as_votable
  acts_as_commentable

  belongs_to :user
  has_many :retweets, dependent: :destroy, foreign_key: 'source_tweet_id'

  validates_presence_of :content
  validates_length_of :content, maximum: 140

  after_create :resolve_mentions

  FORMAT = AutoHtml::Pipeline.new(
    AutoHtml::HtmlEscape.new,
    AutoHtml::Link.new(target: '_blank', rel: 'nofollow'),
    AutoHtml::SimpleFormat.new
  )

  def content=(c)
    super(c)
    self[:content_html] = FORMAT.call(c)
  end

  def resolve_mentions
    mentions = content_html.scan(/@\w+/)

    mentions.uniq.map do |match|
      mention = find_mention(match)
      next unless mention.present?

      update_columns(content_html: replace_mention_with_url(mention, content_html))
      create_activity key: 'tweet.mention', owner: user, recipient: mention
    end
  end

  def find_mention(match)
    User.find_by(username: match.delete('@'))
  end

  def replace_mention_with_url(mention, content)
    content.gsub(/@#{mention.username}/, "<a href='#{Rails.application.routes.url_helpers.user_path(mention.username)}'>@#{mention.username}</a>")
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, except: %i[create]
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      @tweet.create_activity key: 'tweet.created', owner: @tweet.user
      redirect_to user_path(@tweet.user.username, notice: 'تم إنشاء التغردية')
    else
      redirect_to user_path(@tweet.user.username, notice: 'حدث خطأ ما لم يتم انشاء التغريدة')
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to user_path(@tweet.user.username), notice: 'تم تعديل التغريدة'
    else
      redirect_to user_path(@tweet.user.username), notice: 'حدث خطأ لم يتم تعديل التغريدة'
    end
  end

  def destroy
    @tweet.destroy
    redirect_to user_path(@tweet.user.username), notice: 'تم حذف التغريدة'
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
<div class="card my-3">
    <div class="card-header">غرد الان</div>
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.input :content, required: true, autofocus: true, label: false, hint: "#{140 - @tweet.content.to_s.length}", input_html: { class: 'form-control', maxlength: 140, onkeyup: 'updateChars(this); return false;' } %>
      <%= f.button :submit, 'غرد', class: 'btn btn-primary btn-block' %>
    </div>
</div>
<% end %>

<%= javascript_tag do %>
  function updateChars(text){
    $('.tweet_content .form-text').text(140 - text.value.length)
  }
<% end %>

app/views/tweets/_like_and_dislike_button.html.erb
<%= link_to likes_path(likeable_type: 'tweet', likeable_id: tweet.id), remote: true, method: :post, class: 'like' do %>
    <%= button_tag(type: 'button', class: 'btn btn-sm btn-outline-primary') do %>
      <i class="fa fa-thumbs-o-up"></i>
      <span class="badge badge-light"><%= tweet.get_likes.size %></span>
    <% end %>
<% end %>

<%= link_to like_path(likeable_type: 'tweet', likeable_id: tweet.id), remote: true, method: :delete, class: 'dislike' do %>
    <%= button_tag(type: 'button', class: 'btn btn-sm btn-outline-danger') do %>
      <i class="fa fa-thumbs-o-down"></i>
      <span class="badge badge-light"><%= tweet.get_dislikes.size %></span>
    <% end %>
<% end %>

app/views/tweets/_retweet_button.html.erb
<%= link_to retweets_path(tweet_id: tweet.id), method: :post, class: 'retweet' do %>
 <button type="button" class="btn btn-sm btn-success">
   <i class="fa fa-retweet"></i> <span class="badge badge-light"><%= tweet.retweets.size %></span>
 </button>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card mb-3 tweet-<%= tweet.id %>">
    <div class="card-header">
        <%= gravatar_tag tweet.user.email, size: 25, html: {class: 'img-fluid'} %>
        <span><%= tweet.user.username %></span>
        <span>غرد</span>
        <%= content_tag :time, '', class: 'timeago', datetime: tweet.created_at.localtime %>
        <% if user_signed_in? && current_user == @user %>
        <%= link_to 'تعديل', edit_tweet_path(tweet), class: "btn btn-sm btn-primary" %>
        <span>|</span>
        <%= link_to 'حذف', tweet_path(tweet), method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
    </div>
    <div class="card-body">
        <%= raw(tweet.content_html) %>
        <%= render 'tweets/like_and_dislike_button', tweet: tweet %>
        <%= render('tweets/retweet_button', tweet: tweet) if user_signed_in? && tweet.user_id != current_user.id %>
    </div>
    <hr>
    <div class="card-body">
    <%= render 'comments/form', tweet: tweet %>
    </div>
    <div id="comments-<%= tweet.id %>">
      <%= render tweet.comments.reverse %>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="row">
  <div class="col-6 mx-auto">
    <%= render 'form' %>
  </div>
</div>