config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: %i[create destroy]

  get 'pages/timeline'
  post :notifications, to: 'notifications#mark_all_readed'

  resources :tweets, only: %i[create edit update destroy]
  resources :likes, only: %i[create destroy], param: 'likeable_id'
  resources :comments, only: %i[create destroy]
  resources :retweets, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord

  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :massive_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
  has_many :followers, through: :massive_relationships, source: :follower

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :retweets, dependent: :destroy, foreign_key: 'retweeter_id'

  validates_presence_of :username
  validates_uniqueness_of :username

  def follow(user)
    active_relationships.create!(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by_followed_id(user.id).destroy
  end

  def following?(user)
    following.include? user
  end

  def self.mentions(letters)
    return User.none unless letters.present?

    mentions = User.where('username LIKE ?', "%#{letters}%").limit(8)
    mentions.map { |u| { name: u.username } }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :set_user, only: %i[show followers following]

  def index
    @users = if params[:type] == 'followers'
               current_user.followers.order(created_at: :desc).limit(30)
             elsif params[:type] == 'follow'
               current_user.following.order(created_at: :desc).limit(30)
             else
               User.all.order(created_at: :desc).limit(30)
             end
    respond_to do |format|
      format.html
      format.json { render json: User.mentions(params[:q]) }
    end
  end

  def show
    @activities = PublicActivity::Activity.where(owner: @user).or(PublicActivity::Activity.where(recipient: @user)).distinct.order(created_at: :desc)

    @tweet = Tweet.new
    @tweets = @user.retweets + @user.tweets
    @tweets.sort_by!(&:created_at).reverse!
  end

  def followers
    @users = @user.followers.order(created_at: :desc).limit(30)
  end

  def following
    @users = @user.following.order(created_at: :desc).limit(30)
  end

  private

  def set_user
    @user = User.find_by_username(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<% if user_signed_in? && current_user.id != user.id %>
  <% if current_user.following? user %>
    <%= form_for current_user.active_relationships.find_by_followed_id(user.id), html: {method: :delete} do |f| %>
      <%= f.submit "إلغاء المتابعة", class: 'btn btn-dark' %>
    <% end %>
  <% else %>
    <%= form_for current_user.active_relationships.build do |f| %>
      <%= hidden_field_tag :followed_id, user.id %>
      <%= f.submit 'متابعة', class: 'btn btn-dark' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<div class="col-3">
  <%= link_to user_path(user.username) do %>
    <%= gravatar_tag user.email, size: 200, html: { class: 'card-img-top img-fluid' } %>
  <% end %>
  <div class="card-body">
    <h4 class="card-title text-center mb-0">
      <div class="mb-2"><%= user.username %></div>
      <%= render 'follow_button', user: user %>
    </h4>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid text-center">
      <h1 class="mb-3">أشخاص يتابعون <%= @user.username %></h1>
      <hr class="my-3" />
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/following.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid text-center">
      <h1 class="mb-3">أشخاص يتابعهم <%= @user.username %></h1>
      <hr class="my-3" />
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid text-center">
      <h1 class="mb-3">المغردون</h1>
      <div class="btn-group">
        <%= link_to 'الكل', tweeters_path, class: 'btn btn-dark' %>
        <%= link_to 'المتابَعون', tweeters_path(type: 'follow'), class: 'btn btn-dark' %>
        <%= link_to 'المتابِعون', tweeters_path(type: 'followers'), class: 'btn btn-dark' %>
      </div>
      <hr class="my-3" />
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
 
<div class="row">

    <div class="col-md-3">
        <%= gravatar_tag @user.email, size: 500, :html => {:class => 'img-fluid'} %>
    </div>

    <div class="col">
        <div class="jumbtron-fluid">
            <h1 class="display-3">
                <%= @user.username %>
                <div class="btn btn-group">
                  <%= render 'follow_button', user: @user %>
                </div>
            </h1>
            <p class="lead">
            <%= link_to 'المتابِعون', followers_user_path %>: <%= @user.followers.count %>
            |
            <%= link_to 'المتابَعون', following_user_path %>: <%= @user.following.count %>
            </p>
            <p>العمل: <%= @user.age %></p>
            <p>الجنس: <%= @user.gender %></p>
            <hr class="my-3">
            <h1 class="lead"><%= @user.bio %></h1>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-8">
      <% if user_signed_in? && current_user == @user %>
        <%= render 'tweets/form' %>
      <% end %>
      <%= render @tweets %>
    </div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">الأنشطة</div>
            <div class="list-group list-group-flush">
                <%= render_activities(@activities) %>
            </div>
        </div>
    </div>
</div>